---
name: UserManager
main: xenialdan\UserManager\Loader
version: 0.1.0
api: [4.0.0]
load: POSTWORLD
softdepend:
  - DEVirion
authors:
  - XenialDan
description: User management made easy
website: https://github.com/thebigsmileXD/UserManager
permissions:
  usermanager:
    default: true
    children:
      usermanager.version:
        default: true
...
