<?php

declare(strict_types=1);

namespace xenialdan\UserManager\event;

use pocketmine\event\Cancellable;
use pocketmine\Server;

class UserLoginEvent extends UserEvent implements Cancellable
{
    public function call(): void
    {
        Server::getInstance()->getLogger()->info("CALLED " . __METHOD__);
        parent::call(); // TODO: Change the autogenerated stub
    }
}